name: Build and Deploy

on:
  push:
    branches:
      - dev
      - stage
      - main
      - devOps/**

permissions:
  packages: write
  contents: read

jobs:
  # Build Jobs
  build-dev:
    if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/devOps/')
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        id: build
        uses: ./.github/actions/build
        with:
          docker_tag: dev
          docker_file: Dockerfile
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        id: build
        uses: ./.github/actions/build
        with:
          docker_tag: latest
          docker_file: Dockerfile.prod
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  # Deploy Jobs
  deploy-dev:
    needs: build-dev
    if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/devOps/')
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Dev Environment
        uses: ./.github/actions/deploy-only
        with:
          environment: dev
          docker_tag: dev
          node_env: development
          container_name: charik-strapi-dev
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          ssh_key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.DEV_PORT || 22 }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}

  deploy-prod:
    needs: build-prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Production Environment
        uses: ./.github/actions/deploy-only
        with:
          environment: prod
          docker_tag: latest
          node_env: production
          container_name: charik-strapi-prod
          host: ${{ secrets.PROD_HOST || secrets.DEV_HOST}}
          username: ${{ secrets.PROD_USERNAME || secrets.DEV_USERNAME }}
          ssh_key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PROD_PORT || 22 }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}