name: Build and Deploy

on:
  push:
    branches:
      - dev
      - stage
      - main
      - devOps/**

permissions:
  packages: write
  contents: read

jobs:
  build-and-deploy-dev:
    if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/devOps/')
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: ./.github/actions/deploy
        with:
          environment: dev
          docker_tag: dev
          docker_file: Dockerfile
          node_env: development
          container_name: charik-strapi-dev
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          ssh_key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_PORT || 22 }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: ./.github/actions/deploy
        with:
          environment: prod
          docker_tag: latest
          docker_file: Dockerfile.prod
          node_env: production
          container_name: charik-strapi-prod
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          ssh_key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT || 22 }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}